# ---------------------------------------------------------------------------
# 12_tables.R
#
# Tables 1-3 for the manuscript, emitted as markdown to docs/TABLES.md.
#
# Every number here is recomputed from the analytic data rather than copied
# from an earlier script's console output, so the tables and the text cannot
# drift apart.
#
# Definitional note carried throughout: the PRIMARY delirium outcome is
# any_delirium_strict -- documentation of a validated instrument (CAM-ICU or
# ICDSC). The permissive definition, which also counts the 'Symptoms of
# Delirium Present' nursing impression, is reported beside it. Mixing the two
# is the single easiest way to get this manuscript's numbers wrong.
# ---------------------------------------------------------------------------

for (.p in c("R/00_common.R", "00_common.R", "../R/00_common.R"))
  if (file.exists(.p)) { source(.p); break }
if (!exists("PROJ")) stop("run this from the repository root", call. = FALSE)
suppressPackageStartupMessages(library(lme4))

d <- load_cohort()
y <- fread(file.path(PROJ, "data_private", "stay_year.csv"))
d <- merge(d, y, by = "patientunitstayid", all.x = TRUE)
stopifnot(!any(is.na(d$yr)), "any_delirium_strict" %in% names(d))

MIN_YR <- 15
OUT <- file.path(PROJ, "docs", "TABLES.md")
con <- file(OUT, open = "wt", encoding = "UTF-8")
w <- function(...) cat(..., "\n", sep = "", file = con)

# --- small formatting helpers ---------------------------------------------
n_pct  <- function(x, digits = 1) sprintf("%s (%.*f)", format(sum(x, na.rm = TRUE), big.mark = ","), digits, 100 * mean(x, na.rm = TRUE))
med_iqr <- function(x, digits = 0) sprintf("%.*f (%.*f-%.*f)", digits, median(x, na.rm = TRUE),
                                            digits, quantile(x, .25, na.rm = TRUE),
                                            digits, quantile(x, .75, na.rm = TRUE))
pv <- function(p) if (is.na(p)) "--" else if (p < 0.001) "<0.001" else sprintf("%.3f", p)

d14 <- d[yr == 2014]; d15 <- d[yr == 2015]

# ===========================================================================
# TABLE 1 -- cohort characteristics
# ===========================================================================
w("# Tables\n")
w("Generated by `R/12_tables.R`. Percentages are column percentages unless stated.\n")
w("## Table 1. Characteristics of the cohort, overall and by calendar year\n")
w("| Characteristic | Overall (n = ", format(nrow(d), big.mark = ","),
  ") | 2014 (n = ", format(nrow(d14), big.mark = ","),
  ") | 2015 (n = ", format(nrow(d15), big.mark = ","), ") | P |")
w("|---|---|---|---|---|")

row3 <- function(lab, f, p = NA) w("| ", lab, " | ", f(d), " | ", f(d14), " | ", f(d15), " | ", pv(p), " |")

w("| Contributing hospitals, n | ", uniqueN(d$hospitalid), " | ", uniqueN(d14$hospitalid),
  " | ", uniqueN(d15$hospitalid), " | -- |")
row3("Age, y, median (IQR)", function(x) med_iqr(x$age_i),
     wilcox.test(d14$age_i, d15$age_i)$p.value)
row3("Age >89 y (aggregated), n (%)", function(x) n_pct(x$age90),
     prop.test(c(sum(d14$age90), sum(d15$age90)), c(nrow(d14), nrow(d15)))$p.value)
row3("Female sex, n (%)", function(x) n_pct(x$gender == "Female"),
     prop.test(c(sum(d14$gender == "Female", na.rm = TRUE), sum(d15$gender == "Female", na.rm = TRUE)),
               c(nrow(d14), nrow(d15)))$p.value)

w("| **Race/ethnicity, n (%)** | | | | ", pv(chisq.test(table(d$ethnicity, d$yr))$p.value), " |")
for (e in d[!is.na(ethnicity), .N, by = ethnicity][order(-N)]$ethnicity)
  row3(paste0("&nbsp;&nbsp;", e), function(x) n_pct(!is.na(x$ethnicity) & x$ethnicity == e))
row3("&nbsp;&nbsp;Not recorded", function(x) n_pct(is.na(x$ethnicity)))

w("| **ICU type, n (%)** | | | | ", pv(chisq.test(table(d$unittype, d$yr))$p.value), " |")
for (u in d[, .N, by = unittype][order(-N)]$unittype)
  row3(paste0("&nbsp;&nbsp;", u), function(x) n_pct(x$unittype == u))

row3("APACHE IVa score, median (IQR)", function(x) med_iqr(x$apache),
     wilcox.test(d14$apache, d15$apache)$p.value)
row3("Predicted hospital mortality, %, median (IQR)",
     function(x) med_iqr(100 * x$pred_mort_c, 1),
     wilcox.test(d14$pred_mort_c, d15$pred_mort_c)$p.value)
row3("Mechanically ventilated, n (%)", function(x) n_pct(x$ventilated),
     prop.test(c(sum(d14$ventilated), sum(d15$ventilated)), c(nrow(d14), nrow(d15)))$p.value)
row3("ICU length of stay, d, median (IQR)", function(x) med_iqr(x$los_days, 1),
     wilcox.test(d14$los_days, d15$los_days)$p.value)
row3("Died in ICU, n (%)", function(x) n_pct(x$died_icu == 1),
     prop.test(c(sum(d14$died_icu, na.rm = TRUE), sum(d15$died_icu, na.rm = TRUE)),
               c(sum(!is.na(d14$died_icu)), sum(!is.na(d15$died_icu))))$p.value)
row3("Died in hospital, n (%)", function(x) n_pct(x$died_hosp == 1),
     prop.test(c(sum(d14$died_hosp, na.rm = TRUE), sum(d15$died_hosp, na.rm = TRUE)),
               c(sum(!is.na(d14$died_hosp)), sum(!is.na(d15$died_hosp))))$p.value)

w("| **Hospital characteristics (stay level), n (%)** | | | | |")
row3("&nbsp;&nbsp;Teaching", function(x) n_pct(x$teaching == "Teaching"))
row3("&nbsp;&nbsp;Non-teaching", function(x) n_pct(x$teaching == "Non-teaching"))
for (b in levels(d$beds)) row3(paste0("&nbsp;&nbsp;Beds ", b), function(x) n_pct(!is.na(x$beds) & x$beds == b))
row3("&nbsp;&nbsp;Beds not recorded", function(x) n_pct(is.na(x$beds)))
for (r in levels(d$region_f)) row3(paste0("&nbsp;&nbsp;", r), function(x) n_pct(!is.na(x$region_f) & x$region_f == r))
row3("&nbsp;&nbsp;Region not recorded", function(x) n_pct(is.na(x$region_f)))
w("")
w("APACHE = Acute Physiology and Chronic Health Evaluation; ICU = intensive care unit; IQR = interquartile range.")
w("")
w("Age was recorded in aggregated form above 89 years and recoded to 91 for analysis.")
w("")
w("Race/ethnicity, bed size, and census region each include an explicit not-recorded row and therefore sum to 100%.")
w("")
w("Mortality denominators exclude stays with no discharge status recorded (",
  format(sum(is.na(d$died_icu)), big.mark = ","), " for ICU and ",
  format(sum(is.na(d$died_hosp)), big.mark = ","), " for hospital mortality).")
w("")
w("P values compare 2014 with 2015: Wilcoxon rank-sum for continuous variables, chi-squared or test of proportions for categorical. Hospital characteristics are properties of the contributing institution rather than of the calendar year and are not tested.")
w("")
w("APACHE IVa was unavailable for ", format(sum(is.na(d$apache)), big.mark = ","), " stays (",
  sprintf("%.1f%%", 100 * mean(is.na(d$apache))), "): ", format(sum(is.na(d$apache_iva)), big.mark = ","),
  " with no score recorded and ", format(sum(!is.na(d$apache_iva) & d$apache_iva < 0), big.mark = ","),
  " scored -1, the sentinel for an unscorable admission; medians are over stays with a score.\n")

# ===========================================================================
# TABLE 2 -- documented assessment
# ===========================================================================
w("## Table 2. Documented assessment of pain, sedation, and delirium, 2014 to 2015\n")
w("### Panel A. All stays, by calendar year\n")
w("| Assessment | Overall, % | 2014, % | 2015, % | Absolute change, pp | Relative change, % |")
w("|---|---|---|---|---|---|")
els <- list("Delirium, validated instrument (primary)" = "any_delirium_strict",
            "Delirium, any documentation (permissive)" = "any_delirium_assess",
            "Sedation" = "any_sedation_assess",
            "Pain" = "any_pain_assess")
for (nm in names(els)) {
  v <- els[[nm]]
  a <- 100 * mean(d[[v]]); p14 <- 100 * mean(d14[[v]]); p15 <- 100 * mean(d15[[v]])
  w("| ", nm, " | ", sprintf("%.1f", a), " | ", sprintf("%.1f", p14), " | ", sprintf("%.1f", p15),
    " | ", sprintf("%+.1f", p15 - p14), " | ", sprintf("%+.1f", 100 * (p15 - p14) / p14), " |")
}
w("")
w("### Panel B. Within-hospital change, hospitals contributing >= ", MIN_YR,
  " stays in both years\n")
hy <- d[, .(n = .N, del = 100 * mean(any_delirium_strict), sed = 100 * mean(any_sedation_assess),
            pai = 100 * mean(any_pain_assess)), by = .(hospitalid, yr)][n >= MIN_YR]
keep <- intersect(hy[yr == 2014]$hospitalid, hy[yr == 2015]$hospitalid)
h14 <- hy[yr == 2014 & hospitalid %in% keep][order(hospitalid)]
h15 <- hy[yr == 2015 & hospitalid %in% keep][order(hospitalid)]
w("Hospitals characterized in both years: **", length(keep), "**\n")
w("| Assessment | 2014, median % | 2015, median % | Change, pp | Increased, n | Decreased, n | Unchanged, n | P |")
w("|---|---|---|---|---|---|---|---|")
for (nm in c(Delirium = "del", Sedation = "sed", Pain = "pai")) {
  a <- h14[[nm]]; b <- h15[[nm]]
  lab <- names(which(c(Delirium = "del", Sedation = "sed", Pain = "pai") == nm))
  w("| ", lab, " | ", sprintf("%.1f", median(a)), " | ", sprintf("%.1f", median(b)),
    " | ", sprintf("%+.2f", mean(b - a)), " | ", sum(b > a), " | ", sum(b < a), " | ", sum(b == a),
    " | ", pv(wilcox.test(a, b, paired = TRUE)$p.value), " |")
}
w("")
w("Delirium is the validated-instrument definition. P values are Wilcoxon signed-rank tests on paired hospital rates.\n")

w("### Panel C. Intensity of assessment where it occurred\n")
s <- d[any_delirium_strict == 1]
s[, per_day := n_delirium_strict_obs / pmax(los_days, 1)]
ss <- d[any_sedation_assess == 1]; ss[, per_day := n_sedation_obs / pmax(los_days, 1)]
w("| Measure | Delirium | Sedation |")
w("|---|---|---|")
w("| Stays with any documented assessment, n | ", format(nrow(s), big.mark = ","),
  " | ", format(nrow(ss), big.mark = ","), " |")
w("| Time to first assessment, h, median (IQR) | ",
  med_iqr(s$first_delirium_strict_offset / 60, 1), " | -- |")
w("| First assessment within 24 h, % | ",
  sprintf("%.1f", 100 * mean(s$first_delirium_strict_offset <= 1440)), " | -- |")
w("| Assessments per stay, median (IQR) | ", med_iqr(s$n_delirium_strict_obs),
  " | ", med_iqr(ss$n_sedation_obs), " |")
w("| Assessments per ICU day, median | ", sprintf("%.2f", median(s$per_day)),
  " | ", sprintf("%.2f", median(ss$per_day)), " |")
w("| Single isolated assessment, % of screened stays | ",
  sprintf("%.1f", 100 * mean(s$n_delirium_strict_obs == 1)), " | ",
  sprintf("%.1f", 100 * mean(ss$n_sedation_obs == 1)), " |")
w("| >= 2 assessments per ICU day, % of screened stays | ",
  sprintf("%.1f", 100 * mean(s$per_day >= 2)), " | ",
  sprintf("%.1f", 100 * mean(ss$per_day >= 2)), " |")
w("| >= 2 assessments per ICU day, % of **all** stays | ",
  sprintf("%.1f", 100 * sum(s$per_day >= 2) / nrow(d)), " | ",
  sprintf("%.1f", 100 * sum(ss$per_day >= 2) / nrow(d)), " |")
w("")

# ===========================================================================
# TABLE 3 -- hospital-level adoption and variation
# ===========================================================================
w("## Table 3. Hospital-level adoption, between-hospital variation, and predictors of adoption\n")
h <- d[, .(n = .N,
           strict = 100 * mean(any_delirium_strict),
           perm   = 100 * mean(any_delirium_assess),
           sed    = 100 * mean(any_sedation_assess),
           pain   = 100 * mean(any_pain_assess)), by = hospitalid][n >= MIN_STAYS]

w("### Panel A. Adoption, hospitals contributing >= ", MIN_STAYS, " stays (n = ", nrow(h), ")\n")
w("| Definition | Adopters (>=10% of stays), n (%) | Hospitals at exactly 0%, n (%) | Median hospital rate, % | IQR |")
w("|---|---|---|---|---|")
for (nm in c("Delirium, validated instrument" = "strict", "Delirium, any documentation" = "perm",
             "Sedation" = "sed", "Pain" = "pain")) {
  x <- h[[nm]]
  lab <- names(which(c("Delirium, validated instrument" = "strict", "Delirium, any documentation" = "perm",
                       "Sedation" = "sed", "Pain" = "pain") == nm))
  w("| ", lab, " | ", sprintf("%d (%.1f)", sum(x >= 10), 100 * mean(x >= 10)),
    " | ", sprintf("%d (%.1f)", sum(x == 0), 100 * mean(x == 0)),
    " | ", sprintf("%.1f", median(x)),
    " | ", sprintf("%.1f-%.1f", quantile(x, .25), quantile(x, .75)), " |")
}
w("")

w("### Panel B. Number of bundle elements adopted per hospital\n")
h[, k_strict := (pain >= 10) + (sed >= 10) + (strict >= 10)]
h[, k_perm   := (pain >= 10) + (sed >= 10) + (perm   >= 10)]
w("| Elements adopted | Validated definition, n (%) | Permissive definition, n (%) |")
w("|---|---|---|")
for (k in 0:3)
  w("| ", k, " of 3 | ", sprintf("%d (%.1f)", sum(h$k_strict == k), 100 * mean(h$k_strict == k)),
    " | ", sprintf("%d (%.1f)", sum(h$k_perm == k), 100 * mean(h$k_perm == k)), " |")
w("")

w("### Panel C. Between-hospital variation\n")
icc <- function(m) { v <- as.numeric(VarCorr(m)$hospitalid); v / (v + pi^2/3) }
w("| Outcome | Model | ICC | Structural non-adopter fraction (95% CI) | LRT P |")
w("|---|---|---|---|---|")
zibb <- function(col) {
  dat <- d[, .(n = .N, k = sum(get(col))), by = hospitalid][n >= MIN_STAYS]
  f0 <- function(p) { a <- exp(p[1]); b <- exp(p[2])
    -sum(lchoose(dat$n, dat$k) + lbeta(dat$k + a, dat$n - dat$k + b) - lbeta(a, b)) }
  f1 <- function(p) { a <- exp(p[1]); b <- exp(p[2]); pi0 <- plogis(p[3])
    l <- lchoose(dat$n, dat$k) + lbeta(dat$k + a, dat$n - dat$k + b) - lbeta(a, b)
    -sum(ifelse(dat$k == 0, log(pi0 + (1 - pi0) * exp(l)), log(1 - pi0) + l)) }
  A <- optim(c(0, 0), f0, method = "BFGS"); B <- optim(c(A$par, 0), f1, method = "BFGS")
  lr <- 2 * (A$value - B$value)
  set.seed(20260820)
  bs <- replicate(2000, { i <- sample(nrow(dat), replace = TRUE); dd <- dat[i]
    g <- function(p) { a <- exp(p[1]); b <- exp(p[2]); pi0 <- plogis(p[3])
      l <- lchoose(dd$n, dd$k) + lbeta(dd$k + a, dd$n - dd$k + b) - lbeta(a, b)
      -sum(ifelse(dd$k == 0, log(pi0 + (1 - pi0) * exp(l)), log(1 - pi0) + l)) }
    tryCatch(plogis(optim(c(0, 0, 0), g, method = "BFGS")$par[3]), error = function(e) NA_real_) })
  bs <- bs[!is.na(bs)]
  list(pi0 = plogis(B$par[3]), lo = quantile(bs, .025), hi = quantile(bs, .975),
       p = 0.5 * pchisq(lr, 1, lower.tail = FALSE))
}
for (nm in c("Delirium, validated instrument" = "any_delirium_strict",
             "Sedation" = "any_sedation_assess", "Pain" = "any_pain_assess")) {
  lab <- names(which(c("Delirium, validated instrument" = "any_delirium_strict",
                       "Sedation" = "any_sedation_assess", "Pain" = "any_pain_assess") == nm))
  m <- glmer(as.formula(sprintf("%s ~ 1 + (1|hospitalid)", nm)), data = d, family = binomial, nAGQ = 0)
  z <- zibb(nm)
  w("| ", lab, " | Empty | ", sprintf("%.3f", icc(m)),
    " | ", sprintf("%.2f (%.2f-%.2f)", z$pi0, z$lo, z$hi), " | ", pv(z$p), " |")
}
dd <- d[!is.na(gender)]
m_adj <- glmer(any_delirium_strict ~ ventilated + scale(age_i) + gender + scale(los_days) +
                 unit_f + (1 | hospitalid), data = dd, family = binomial, nAGQ = 0)
m_un  <- glmer(any_delirium_strict ~ 1 + (1 | hospitalid), data = dd, family = binomial, nAGQ = 0)
w("| Delirium, validated instrument | Case-mix adjusted | ", sprintf("%.3f", icc(m_adj)), " | -- | -- |")
w("")
w("Case-mix model adjusted for mechanical ventilation, age, sex, ICU length of stay, and ICU type. ",
  "Between-hospital variance retained after adjustment: ",
  sprintf("%.1f%%", 100 * as.numeric(VarCorr(m_adj)$hospitalid) / as.numeric(VarCorr(m_un)$hospitalid)), ". ",
  "The median odds ratio is not reported: with a large proportion of hospitals at exactly zero the model ",
  "approaches quasi-separation and the statistic is unstable.\n")

w("### Panel D. Hospital-level predictors of delirium-screening adoption\n")
hh <- merge(h[, .(hospitalid, n, strict)],
            unique(d[, .(hospitalid, teaching, beds, region_f)]), by = "hospitalid")
hh[, adopter := as.integer(strict >= 10)][, size_k := n / 100]
hc <- hh[!is.na(teaching) & !is.na(beds) & !is.na(region_f)]
fit <- glm(adopter ~ teaching + beds + region_f + size_k, data = hc, family = binomial)
ci <- suppressMessages(confint(fit)); sm <- summary(fit)$coefficients
labs <- c(teachingTeaching = "Teaching hospital (vs non-teaching)",
          `beds100 - 249` = "100-249 beds (vs <100)", `beds250 - 499` = "250-499 beds (vs <100)",
          `beds>= 500` = ">=500 beds (vs <100)", region_fSouth = "South (vs Midwest)",
          region_fWest = "West (vs Midwest)", region_fNortheast = "Northeast (vs Midwest)",
          size_k = "Cohort size, per 100 stays")
w("| Predictor | Odds ratio (95% CI) | P |")
w("|---|---|---|")
for (i in 2:nrow(sm))
  w("| ", labs[[rownames(sm)[i]]], " | ",
    sprintf("%.2f (%.2f-%.2f)", exp(sm[i,1]), exp(ci[i,1]), exp(ci[i,2])), " | ", pv(sm[i,4]), " |")
lrt <- anova(glm(adopter ~ 1, data = hc, family = binomial), fit, test = "LRT")
ph <- predict(fit, type = "response"); n1 <- sum(hc$adopter); n0 <- nrow(hc) - n1
auc <- (sum(rank(ph)[hc$adopter == 1]) - n1 * (n1 + 1) / 2) / (n1 * n0)
dm <- d[hospitalid %in% hc$hospitalid & !is.na(teaching) & !is.na(beds) & !is.na(region_f)]
v0 <- as.numeric(VarCorr(glmer(any_delirium_strict ~ 1 + (1|hospitalid), data = dm,
                               family = binomial, nAGQ = 0))$hospitalid)
v1 <- as.numeric(VarCorr(glmer(any_delirium_strict ~ teaching + beds + region_f + (1|hospitalid),
                               data = dm, family = binomial, nAGQ = 0))$hospitalid)
w("")
w("Complete cases: ", nrow(hc), " of ", nrow(hh), " hospitals. Joint likelihood ratio test P ",
  pv(lrt$`Pr(>Chi)`[2]), "; McFadden pseudo-R2 ", sprintf("%.3f", 1 - fit$deviance / fit$null.deviance),
  "; area under the curve ", sprintf("%.3f", auc), ". ",
  "Hospital characteristics explained ", sprintf("%.1f%%", 100 * (v0 - v1) / v0),
  " of the between-hospital variance, moving the ICC from ", sprintf("%.3f", v0/(v0 + pi^2/3)),
  " to ", sprintf("%.3f", v1/(v1 + pi^2/3)), ".\n")

close(con)
cat("wrote", OUT, "\n")
